// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkfyhlrlpbriqglmujpy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdrZnlobHJscGJyaXFnbG11anB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3ODQyMjQsImV4cCI6MjA1NzM2MDIyNH0.5HMuk-6LrgakYTxGM4OJs5V3BqD_mgZ7dhPLm_tmFnU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);